
#ifndef BOOST_FUNCTIONAL_CONFIG_HPP_
#define BOOST_FUNCTIONAL_CONFIG_HPP_

#ifndef BOOST_FUNCTIONAL_CONFIG_ARITY_MAX 
#define BOOST_FUNCTIONAL_CONFIG_ARITY_MAX 5
#endif

#ifndef BOOST_FUNCTIONAL_CONFIG_OVERLOAD_MAX
#define BOOST_FUNCTIONAL_CONFIG_OVERLOAD_MAX 5
#endif

#endif // #include guard

