#ifndef BOOST_GENERIC_DETAIL_POP_LAST_ARG_HPP
#define BOOST_GENERIC_DETAIL_POP_LAST_ARG_HPP

#define BOOST_GENERIC_DETAIL_POP_LAST_ARG( ... )                               \


#endif // BOOST_GENERIC_DETAIL_POP_LAST_ARG_HPP
