#ifndef BOOST_SIMD_TOOLBOX_CONSTANT_CONSTANTS_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_CONSTANT_CONSTANTS_HPP_INCLUDED

#include <boost/simd/toolbox/constant/include/constants/cgold.hpp>
#include <boost/simd/toolbox/constant/include/constants/digits.hpp>
#include <boost/simd/toolbox/constant/include/constants/eight.hpp>
#include <boost/simd/toolbox/constant/include/constants/eleven.hpp>
#include <boost/simd/toolbox/constant/include/constants/eps.hpp>
#include <boost/simd/toolbox/constant/include/constants/eps_related.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_10.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_11.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_12.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_4.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_5.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_6.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_7.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_8.hpp>
#include <boost/simd/toolbox/constant/include/constants/fact_9.hpp>
#include <boost/simd/toolbox/constant/include/constants/false.hpp>
#include <boost/simd/toolbox/constant/include/constants/five.hpp>
#include <boost/simd/toolbox/constant/include/constants/four.hpp>
#include <boost/simd/toolbox/constant/include/constants/fourthrooteps.hpp>
#include <boost/simd/toolbox/constant/include/constants/gold.hpp>
#include <boost/simd/toolbox/constant/include/constants/half.hpp>
#include <boost/simd/toolbox/constant/include/constants/halfeps.hpp>
#include <boost/simd/toolbox/constant/include/constants/ieee.hpp>
#include <boost/simd/toolbox/constant/include/constants/inf.hpp>
#include <boost/simd/toolbox/constant/include/constants/infinites.hpp>
#include <boost/simd/toolbox/constant/include/constants/int_splat.hpp>
#include <boost/simd/toolbox/constant/include/constants/ldexpmask.hpp>
#include <boost/simd/toolbox/constant/include/constants/maxexponent.hpp>
#include <boost/simd/toolbox/constant/include/constants/maxleftshift.hpp>
#include <boost/simd/toolbox/constant/include/constants/meight.hpp>
#include <boost/simd/toolbox/constant/include/constants/mfive.hpp>
#include <boost/simd/toolbox/constant/include/constants/mfour.hpp>
#include <boost/simd/toolbox/constant/include/constants/mhalf.hpp>
#include <boost/simd/toolbox/constant/include/constants/mindenormal.hpp>
#include <boost/simd/toolbox/constant/include/constants/minexponent.hpp>
#include <boost/simd/toolbox/constant/include/constants/minf.hpp>
#include <boost/simd/toolbox/constant/include/constants/mlogeps2.hpp>
#include <boost/simd/toolbox/constant/include/constants/mnine.hpp>
#include <boost/simd/toolbox/constant/include/constants/mone.hpp>
#include <boost/simd/toolbox/constant/include/constants/mseven.hpp>
#include <boost/simd/toolbox/constant/include/constants/msix.hpp>
#include <boost/simd/toolbox/constant/include/constants/mten.hpp>
#include <boost/simd/toolbox/constant/include/constants/mthree.hpp>
#include <boost/simd/toolbox/constant/include/constants/mtwo.hpp>
#include <boost/simd/toolbox/constant/include/constants/mzero.hpp>
#include <boost/simd/toolbox/constant/include/constants/nan.hpp>
#include <boost/simd/toolbox/constant/include/constants/nbdigits.hpp>
#include <boost/simd/toolbox/constant/include/constants/nbexponentbits.hpp>
#include <boost/simd/toolbox/constant/include/constants/nbmantissabits.hpp>
#include <boost/simd/toolbox/constant/include/constants/nine.hpp>
#include <boost/simd/toolbox/constant/include/constants/one.hpp>
#include <boost/simd/toolbox/constant/include/constants/pi.hpp>
#include <boost/simd/toolbox/constant/include/constants/properties.hpp>
#include <boost/simd/toolbox/constant/include/constants/quarter.hpp>
#include <boost/simd/toolbox/constant/include/constants/real.hpp>
#include <boost/simd/toolbox/constant/include/constants/real_splat.hpp>
#include <boost/simd/toolbox/constant/include/constants/seven.hpp>
#include <boost/simd/toolbox/constant/include/constants/signmask.hpp>
#include <boost/simd/toolbox/constant/include/constants/six.hpp>
#include <boost/simd/toolbox/constant/include/constants/smallestposval.hpp>
#include <boost/simd/toolbox/constant/include/constants/splitfactor.hpp>
#include <boost/simd/toolbox/constant/include/constants/sqrt_2.hpp>
#include <boost/simd/toolbox/constant/include/constants/sqrt_2o_2.hpp>
#include <boost/simd/toolbox/constant/include/constants/sqrteps.hpp>
#include <boost/simd/toolbox/constant/include/constants/ten.hpp>
#include <boost/simd/toolbox/constant/include/constants/third.hpp>
#include <boost/simd/toolbox/constant/include/constants/thirdrooteps.hpp>
#include <boost/simd/toolbox/constant/include/constants/thousand.hpp>
#include <boost/simd/toolbox/constant/include/constants/three.hpp>
#include <boost/simd/toolbox/constant/include/constants/threeeps.hpp>
#include <boost/simd/toolbox/constant/include/constants/true.hpp>
#include <boost/simd/toolbox/constant/include/constants/true_false.hpp>
#include <boost/simd/toolbox/constant/include/constants/twelve.hpp>
#include <boost/simd/toolbox/constant/include/constants/twenty.hpp>
#include <boost/simd/toolbox/constant/include/constants/two.hpp>
#include <boost/simd/toolbox/constant/include/constants/twotom10.hpp>
#include <boost/simd/toolbox/constant/include/constants/twotonmb.hpp>
#include <boost/simd/toolbox/constant/include/constants/valmax.hpp>
#include <boost/simd/toolbox/constant/include/constants/valmin.hpp>
#include <boost/simd/toolbox/constant/include/constants/zero.hpp>

#endif
