#ifndef BOOST_SIMD_TOOLBOX_CONSTANT_INCLUDE_CONSTANTS_TEN_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_CONSTANT_INCLUDE_CONSTANTS_TEN_HPP_INCLUDED

#include <boost/simd/toolbox/constant/constants/ten.hpp>

#endif
