#ifndef BOOST_SIMD_TOOLBOX_CONSTANT_INCLUDE_CONSTANTS_TWO_HPP_INCLUDED
#define BOOST_SIMD_TOOLBOX_CONSTANT_INCLUDE_CONSTANTS_TWO_HPP_INCLUDED

#include <boost/simd/toolbox/constant/constants/two.hpp>

#endif
