#ifndef NT2_TOOLBOX_ARITHMETIC_FUNCTIONS_HPP_INCLUDED
#define NT2_TOOLBOX_ARITHMETIC_FUNCTIONS_HPP_INCLUDED

#include <nt2/toolbox/arithmetic/include/functions/abs.hpp>
#include <nt2/toolbox/arithmetic/include/functions/abss.hpp>
#include <nt2/toolbox/arithmetic/include/functions/adds.hpp>
#include <nt2/toolbox/arithmetic/include/functions/amul.hpp>
#include <nt2/toolbox/arithmetic/include/functions/arg.hpp>
#include <nt2/toolbox/arithmetic/include/functions/average.hpp>
#include <nt2/toolbox/arithmetic/include/functions/ceil.hpp>
#include <nt2/toolbox/arithmetic/include/functions/correct_fma.hpp>
#include <nt2/toolbox/arithmetic/include/functions/dist.hpp>
#include <nt2/toolbox/arithmetic/include/functions/divceil.hpp>
#include <nt2/toolbox/arithmetic/include/functions/divfix.hpp>
#include <nt2/toolbox/arithmetic/include/functions/divfloor.hpp>
#include <nt2/toolbox/arithmetic/include/functions/divround.hpp>
#include <nt2/toolbox/arithmetic/include/functions/divs.hpp>
#include <nt2/toolbox/arithmetic/include/functions/fam.hpp>
#include <nt2/toolbox/arithmetic/include/functions/fast_hypot.hpp>
#include <nt2/toolbox/arithmetic/include/functions/fast_toint.hpp>
#include <nt2/toolbox/arithmetic/include/functions/floor.hpp>
#include <nt2/toolbox/arithmetic/include/functions/fma.hpp>
#include <nt2/toolbox/arithmetic/include/functions/hypot.hpp>
#include <nt2/toolbox/arithmetic/include/functions/iceil.hpp>
#include <nt2/toolbox/arithmetic/include/functions/idivceil.hpp>
#include <nt2/toolbox/arithmetic/include/functions/idivfix.hpp>
#include <nt2/toolbox/arithmetic/include/functions/idivfloor.hpp>
#include <nt2/toolbox/arithmetic/include/functions/idivround.hpp>
#include <nt2/toolbox/arithmetic/include/functions/ifix.hpp>
#include <nt2/toolbox/arithmetic/include/functions/ifloor.hpp>
#include <nt2/toolbox/arithmetic/include/functions/iround.hpp>
#include <nt2/toolbox/arithmetic/include/functions/iround2even.hpp>
#include <nt2/toolbox/arithmetic/include/functions/itrunc.hpp>
#include <nt2/toolbox/arithmetic/include/functions/ldiv.hpp>
#include <nt2/toolbox/arithmetic/include/functions/ldivide.hpp>
#include <nt2/toolbox/arithmetic/include/functions/logical_xor.hpp>
#include <nt2/toolbox/arithmetic/include/functions/madd.hpp>
#include <nt2/toolbox/arithmetic/include/functions/max.hpp>
#include <nt2/toolbox/arithmetic/include/functions/min.hpp>
#include <nt2/toolbox/arithmetic/include/functions/minmod.hpp>
#include <nt2/toolbox/arithmetic/include/functions/minusone.hpp>
#include <nt2/toolbox/arithmetic/include/functions/mod.hpp>
#include <nt2/toolbox/arithmetic/include/functions/muls.hpp>
#include <nt2/toolbox/arithmetic/include/functions/negs.hpp>
#include <nt2/toolbox/arithmetic/include/functions/oneminus.hpp>
#include <nt2/toolbox/arithmetic/include/functions/oneplus.hpp>
#include <nt2/toolbox/arithmetic/include/functions/random.hpp>
#include <nt2/toolbox/arithmetic/include/functions/rdivide.hpp>
#include <nt2/toolbox/arithmetic/include/functions/rec.hpp>
#include <nt2/toolbox/arithmetic/include/functions/rem.hpp>
#include <nt2/toolbox/arithmetic/include/functions/remainder.hpp>
#include <nt2/toolbox/arithmetic/include/functions/remquo.hpp>
#include <nt2/toolbox/arithmetic/include/functions/round.hpp>
#include <nt2/toolbox/arithmetic/include/functions/rsqrt.hpp>
#include <nt2/toolbox/arithmetic/include/functions/sqr.hpp>
#include <nt2/toolbox/arithmetic/include/functions/sqrt.hpp>
#include <nt2/toolbox/arithmetic/include/functions/subs.hpp>
#include <nt2/toolbox/arithmetic/include/functions/tofloat.hpp>
#include <nt2/toolbox/arithmetic/include/functions/toint.hpp>
#include <nt2/toolbox/arithmetic/include/functions/trunc.hpp>
#include <nt2/toolbox/arithmetic/include/functions/two_add.hpp>
#include <nt2/toolbox/arithmetic/include/functions/two_prod.hpp>
#include <nt2/toolbox/arithmetic/include/functions/two_split.hpp>

#endif
