
// Copyright (C) 2008-2013 Lorenzo Caminiti
// Distributed under the Boost Software License, Version 1.0
// (see accompanying file LICENSE_1_0.txt or a copy at
// http://www.boost.org/LICENSE_1_0.txt)
// http://www.boost.org/doc/libs/release/libs/contract/doc/html/index.html

#ifndef BOOST_CONTRACT_AUX_CONFIG_HPP_
#define BOOST_CONTRACT_AUX_CONFIG_HPP_

#include <boost/contract/config.hpp>
#include <boost/config.hpp>

// Internal option to enable debug prints to `clog` (programmers should never
// need to access this).
#ifdef BOOST_CONTRACT_AUX_CONFIG_DEBUG
#   define BOOST_CONTRACT_AUX_CONFIG_DEBUG_01 1
#else
#   define BOOST_CONTRACT_AUX_CONFIG_DEBUG_01 0
#endif

// Internal option to change named parameter tag namespace (programmers
// should never need to access this).
#ifndef BOOST_CONTRACT_AUX_CONFIG_NAMED_PARAMETER_TAG_NAMESPACE_DEFAULT
#   define BOOST_CONTRACT_AUX_CONFIG_NAMED_PARAMETER_TAG_NAMESPACE_DEFAULT \
        BOOST_CONTRACT_AUX_SYMBOL( (params) )
#endif

#ifdef BOOST_CONTRACT_CONFIG_THREAD_SAFE
#   define BOOST_CONTRACT_AUX_CONFIG_THREAD_SAFE_01 1
#else
#   define BOOST_CONTRACT_AUX_CONFIG_THREAD_SAFE_01 0
#endif

#ifdef BOOST_CONTRACT_CONFIG_NO_PRECONDITIONS
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITIONS_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITIONS_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_NO_POSTCONDITIONS
#   define BOOST_CONTRACT_AUX_CONFIG_POSTCONDITIONS_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_POSTCONDITIONS_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_NO_CLASS_INVARIANTS
#   define BOOST_CONTRACT_AUX_CONFIG_CLASS_INVARIANTS_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_CLASS_INVARIANTS_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_NO_BLOCK_INVARIANTS
#   define BOOST_CONTRACT_AUX_CONFIG_BLOCK_INVARIANTS_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_BLOCK_INVARIANTS_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_NO_LOOP_VARIANTS
#   define BOOST_CONTRACT_AUX_CONFIG_LOOP_VARIANTS_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_LOOP_VARIANTS_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_DO_NOT_OVERRIDE_PRECONDITIONS
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITION_OVERRIDE_01 0
#else
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITION_OVERRIDE_01 1
#endif

#ifdef BOOST_CONTRACT_CONFIG_REPORT_OVERRIDDEN_PRECONDITION_FAILURE
#   define BOOST_CONTRACT_AUX_CONFIG_REPORT_OVERRIDDEN_PRECONDITION_FAILURE_01 1
#else
#   define BOOST_CONTRACT_AUX_CONFIG_REPORT_OVERRIDDEN_PRECONDITION_FAILURE_01 0
#endif

#ifdef BOOST_CONTRACT_CONFIG_PRECONDITIONS_DISABLE_NO_ASSERTION
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITIONS_DISABLE_NO_ASSERTION_01 1
#else
#   define BOOST_CONTRACT_AUX_CONFIG_PRECONDITIONS_DISABLE_NO_ASSERTION_01 0
#endif

#endif // #include guard

