#ifndef BOOST_SIMD_INCLUDE_FUNCTIONS_COMPARE_NOT_EQUAL_HPP_INCLUDED
#define BOOST_SIMD_INCLUDE_FUNCTIONS_COMPARE_NOT_EQUAL_HPP_INCLUDED

#include <boost/simd/toolbox/operator/include/functions/compare_not_equal.hpp>

#endif
