#ifndef BOOST_SIMD_INCLUDE_FUNCTIONS_IS_EQUAL_WITH_EQUAL_NANS_HPP_INCLUDED
#define BOOST_SIMD_INCLUDE_FUNCTIONS_IS_EQUAL_WITH_EQUAL_NANS_HPP_INCLUDED

#include <boost/simd/toolbox/predicates/include/functions/is_equal_with_equal_nans.hpp>

#endif
